name: Test SSH Connection and File Transfer

on:
  push:
    branches: [ master ] # Mudança de 'main' para 'master' para corresponder ao seu workflow

jobs:
  test-ssh-and-transfer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "echo 'SSH Connection Successful'"

      - name: Create a Test File
        run: echo "This is a test file." > testfile.txt

      - name: Transfer Test File to Server via SSH
        run: scp -o StrictHostKeyChecking=no testfile.txt root@${{ secrets.SERVER_IP }}:/home/saudeemequilibrio/

      # Opcional: Você pode adicionar um passo para verificar se o arquivo foi transferido
      - name: Check File Existence
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "ls -l /home/saudeemequilibrio/testfile.txt && echo 'File transfer successful'"
